services:
  - type: web
    name: pionex-trading-bot
    env: python
    plan: free
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: |
      chmod +x start.sh
      ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIONEX_API_KEY
        sync: false
      - key: PIONEX_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
    healthCheckPath: /health
    autoDeploy: true 